# This files gather compiler flags that are common to g++, clang and
# pathCC

cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wall" "W" "Wextra" "pedantic" "Wshadow")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wpointer-arith" "Wcast-qual" "Wcast-align")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wwrite-strings" "Wctor-dtor-privacy" "Wnon-virtual-dtor")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Woverloaded-virtual" "Wreturn-type")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wendif-labels" "Wsign-compare" "Wmissing-format-attribute")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wmultichar" "Wdeprecated-declarations" "Wpacked")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wredundant-decls")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wunknown-pragmas" "Wundef" "Wreorder")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wconversion")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Winit-self")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wlogical-op")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wmissing-declarations")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wmissing-include-dirs")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wnoexcept")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsign-promo")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wstrict-null-sentinel")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wtrampolines")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wvector-operation-performance")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wzero-as-null-pointer-constant")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wignored-qualifiers")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsequence-point")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wswitch")

# cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-attribute=pure")
# cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-attribute=const")
# cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-attribute=noreturn")
# cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-attribute=format")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-final-types")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-final-methods")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-override")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wswitch-bool")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wlogical-not-parentheses")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsizeof-array-argument")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wbool-compare")
cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-strict-aliasing")

# cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Winline")
# cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsign-conversion")
# cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wold-style-cast")
# cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wdouble-promotion")
# cadna_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wdouble-promotion")